apiVersion: v1
kind: Service
metadata:
  name: bind-svc
spec:
  type: LoadBalancer
  ports:
  - name: udp
    protocol: UDP
    port: 53
    targetPort: 53
  selector:
    app: bind
---
apiVersion: v1
kind: Service
metadata:
  name: bind-svc-tcp
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    protocol: TCP
    port: 53
    targetPort: 53
  selector:
    app: bind
---
apiVersion: v1
kind: Service
metadata:
  name: bind-web
spec:
  type: LoadBalancer
  ports:
  - port: 10000
    targetPort: 10000
  selector:
    app: bind
